<?php

namespace App\Controller\Admin;

use App\Entity\Works;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class WorksCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Works::class;
    }

    public function createEntity(string $entityFqcn)
    {
        parent::createEntity($entityFqcn); // TODO: Change the autogenerated stub
        $works = new Works();
        $works->setUser($this->getUser());
        return $works;
    }

    public function configureFields(string $pageName): iterable
    {
        //dd($this->getUser()->getId());
        return [
            TextField::new('title'),
            TextField::new('description'),
            AssociationField::new('categories')->renderAsNativeWidget(),
            ImageField::new('filesOrlinks')->setUploadDir('public/uploads'),
        ];
    }

}
